import jsPDF from 'jspdf'

export default function ClaimBrief({ claimData, onReset }) {
    if (!claimData) return null

    const downloadPDF = () => {
        try {
            console.log('Generating PDF for claim:', claimData)

            const doc = new jsPDF()
            const pageWidth = doc.internal.pageSize.getWidth()
            const margin = 20
            let yPos = 20

            // Helper function to add text with word wrap
            const addText = (text, fontSize = 12, isBold = false) => {
                if (!text) text = 'N/A'
                doc.setFontSize(fontSize)
                if (isBold) doc.setFont(undefined, 'bold')
                else doc.setFont(undefined, 'normal')

                const lines = doc.splitTextToSize(String(text), pageWidth - 2 * margin)
                doc.text(lines, margin, yPos)
                yPos += lines.length * (fontSize * 0.5) + 5
            }

            // Title
            addText(`Claim Brief #${claimData.id || 'Unknown'}`, 18, true)
            addText(`Generated: ${new Date().toLocaleDateString()}`, 10)
            yPos += 5

            // Claim Summary
            addText('CLAIM SUMMARY', 14, true)
            addText(`Claimant: ${claimData.name || 'N/A'}`)
            addText(`Employee ID: ${claimData.employeeId || 'N/A'}`)
            addText(`Incident Type: ${claimData.incidentType || 'N/A'}`)
            addText(`Severity: ${claimData.severity || 'N/A'}`)
            addText(`Description: ${claimData.description || 'N/A'}`)
            yPos += 10

            // Triage Decision
            addText('TRIAGE DECISION', 14, true)
            addText(`Decision: ${claimData.decision || 'N/A'}`)
            addText(`Status: ${claimData.status || 'N/A'}`)
            addText(`Fraud Risk: ${claimData.fraudRisk || 'Low'}`)
            addText(`Reasoning: ${claimData.reasoning || claimData.rationale || 'N/A'}`)
            yPos += 10

            // Next Steps
            if (claimData.nextSteps && claimData.nextSteps.length > 0) {
                addText('RECOMMENDED NEXT STEPS', 14, true)
                claimData.nextSteps.forEach((step, idx) => {
                    addText(`${idx + 1}. ${step}`)
                })
                yPos += 10
            }

            // Official Report
            if (claimData.officialReport) {
                addText('OFFICIAL REPORT', 14, true)
                addText(claimData.officialReport)
            }

            // Save PDF
            const filename = `Claim_${claimData.id || 'Unknown'}_${new Date().toISOString().split('T')[0]}.pdf`
            console.log('Saving PDF as:', filename)
            doc.save(filename)
            console.log('PDF generated successfully!')
        } catch (error) {
            console.error('Error generating PDF:', error)
            alert(`Failed to generate PDF: ${error.message}`)
        }
    }

    return (
        <div className="fade-in">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
                <div>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: '700' }}>Claim Brief #{claimData.id}</h2>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <p style={{ color: 'hsl(var(--color-text-muted))', margin: 0 }}>Generated by Report & Next-Step Agent</p>
                        <span style={{ fontSize: '0.7rem', padding: '0.25rem 0.5rem', backgroundColor: 'hsl(var(--color-success))', color: 'white', borderRadius: 'var(--radius-sm)', fontWeight: '600' }}>🤖 AGENT 3</span>
                    </div>
                </div>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <button className="btn btn-primary" onClick={downloadPDF}>
                        📄 Download PDF
                    </button>
                    <button className="btn btn-secondary" onClick={onReset}>Close Brief</button>
                </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '1.5rem' }}>

                {/* Left Column */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                    {/* Summary Card */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem', borderBottom: '1px solid hsl(var(--color-text-light) / 0.1)', paddingBottom: '0.5rem' }}>Claim Summary</h3>
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                            <div>
                                <label className="label">Claimant</label>
                                <div style={{ fontWeight: '500' }}>{claimData.name}</div>
                            </div>
                            <div>
                                <label className="label">Employee ID</label>
                                <div style={{ fontWeight: '500' }}>{claimData.employeeId}</div>
                            </div>
                            <div style={{ gridColumn: 'span 2' }}>
                                <label className="label">Incident Description</label>
                                <p style={{ lineHeight: '1.5' }}>{claimData.description}</p>
                            </div>
                        </div>
                    </div>

                    {/* Agent Reasoning Card */}
                    <div className="card" style={{ backgroundColor: 'hsl(var(--color-success) / 0.05)', border: '1px solid hsl(var(--color-success) / 0.2)' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
                            <h3 style={{ margin: 0, color: 'hsl(var(--color-success))' }}>🤖 Triage Decision Agent</h3>
                            <span style={{ fontSize: '0.7rem', padding: '0.25rem 0.5rem', backgroundColor: 'hsl(var(--color-success))', color: 'white', borderRadius: 'var(--radius-sm)', fontWeight: '600' }}>AGENT 2</span>
                        </div>
                        <p style={{ marginBottom: '1rem' }}>
                            Based on the reported <strong>{claimData.severity} damage</strong> and incident type, this agent has determined the following:
                        </p>

                        {/* Risk & Action Grid */}
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1.5rem' }}>
                            <div style={{ padding: '0.5rem 1rem', backgroundColor: 'white', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-sm)' }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.25rem' }}>
                                    <div className="label" style={{ margin: 0 }}>Fraud Risk</div>
                                    <span style={{ fontSize: '0.6rem', padding: '0.2rem 0.4rem', backgroundColor: 'hsl(var(--color-success))', color: 'white', borderRadius: 'var(--radius-sm)', fontWeight: '600' }}>🤖 AGENT 2.1</span>
                                </div>
                                <div style={{
                                    fontSize: '1.25rem',
                                    fontWeight: '700',
                                    color: claimData.fraudRisk === 'High' ? 'hsl(var(--color-danger))' : 'hsl(var(--color-success))'
                                }}>
                                    {claimData.fraudRisk || 'Low'}
                                </div>
                                <div style={{ fontSize: '0.75rem', color: 'hsl(var(--color-text-muted))', marginTop: '0.25rem' }}>
                                    {claimData.fraudReasoning || 'No inconsistencies detected.'}
                                </div>
                            </div>
                            <div style={{ padding: '0.5rem 1rem', backgroundColor: 'white', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-sm)' }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.25rem' }}>
                                    <div className="label" style={{ margin: 0 }}>Recommended Action</div>
                                    <span style={{ fontSize: '0.6rem', padding: '0.2rem 0.4rem', backgroundColor: 'hsl(var(--color-success))', color: 'white', borderRadius: 'var(--radius-sm)', fontWeight: '600' }}>🤖 AGENT 2.2</span>
                                </div>
                                <div style={{ fontSize: '1.25rem', fontWeight: '700', color: 'hsl(var(--color-primary))' }}>
                                    {claimData.recommendedAction || claimData.decision}
                                </div>
                            </div>
                        </div>

                        {/* Future Steps & Suggestions */}
                        {claimData.futureSteps && (
                            <div style={{ marginBottom: '1rem' }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
                                    <h4 style={{ fontSize: '0.9rem', fontWeight: '600', margin: 0 }}>Next Steps</h4>
                                    <span style={{ fontSize: '0.6rem', padding: '0.2rem 0.4rem', backgroundColor: 'hsl(var(--color-success))', color: 'white', borderRadius: 'var(--radius-sm)', fontWeight: '600' }}>🤖 AGENT 3.1</span>
                                </div>
                                <ul style={{ paddingLeft: '1.5rem', fontSize: '0.9rem', color: 'hsl(var(--color-text-main))' }}>
                                    {claimData.futureSteps.map((step, i) => (
                                        <li key={i} style={{ marginBottom: '0.25rem' }}>{step}</li>
                                    ))}
                                </ul>
                            </div>
                        )}

                        {claimData.employeeSuggestions && (
                            <div style={{ padding: '0.75rem', backgroundColor: 'hsl(var(--color-success) / 0.1)', borderRadius: 'var(--radius-md)', border: '1px solid hsl(var(--color-success) / 0.2)' }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
                                    <h4 style={{ fontSize: '0.9rem', fontWeight: '600', margin: 0, color: 'hsl(var(--color-success))' }}>💡 Employee Suggestions</h4>
                                    <span style={{ fontSize: '0.6rem', padding: '0.2rem 0.4rem', backgroundColor: 'hsl(var(--color-success))', color: 'white', borderRadius: 'var(--radius-sm)', fontWeight: '600' }}>🤖 AGENT 3.2</span>
                                </div>
                                <p style={{ fontSize: '0.9rem', margin: 0 }}>{claimData.employeeSuggestions}</p>
                            </div>
                        )}
                    </div>
                    {/* Official Report (if exists) */}
                    {claimData.officialReport && (
                        <div className="card" style={{ border: '1px solid hsl(var(--color-success))', marginBottom: '1.5rem' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
                                <h3 style={{ margin: 0, color: 'hsl(var(--color-success))' }}>📄 Official Company Report</h3>
                                <span style={{ fontSize: '0.7rem', padding: '0.25rem 0.5rem', backgroundColor: 'hsl(var(--color-success))', color: 'white', borderRadius: 'var(--radius-sm)', fontWeight: '600' }}>🤖 AGENT 3</span>
                            </div>
                            <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit', fontSize: '0.9rem', color: 'hsl(var(--color-text-main))' }}>
                                {claimData.officialReport}
                            </pre>
                        </div>
                    )}

                    {/* Transcript Viewer */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem' }}>💬 Conversation Transcript</h3>
                        <div style={{ maxHeight: '300px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.75rem', paddingRight: '0.5rem' }}>
                            {claimData.transcript && claimData.transcript.length > 0 ? (
                                claimData.transcript.map((msg, idx) => (
                                    <div key={idx} style={{
                                        alignSelf: msg.role === 'user' ? 'flex-end' : 'flex-start',
                                        backgroundColor: msg.role === 'user' ? 'hsl(var(--color-primary) / 0.1)' : 'hsl(var(--color-surface))',
                                        color: 'hsl(var(--color-text))',
                                        padding: '0.5rem 0.75rem',
                                        borderRadius: '0.5rem',
                                        maxWidth: '90%',
                                        fontSize: '0.85rem',
                                        border: msg.role === 'user' ? '1px solid hsl(var(--color-primary) / 0.2)' : '1px solid hsl(var(--color-border))'
                                    }}>
                                        <div style={{ fontSize: '0.7rem', fontWeight: '600', marginBottom: '0.25rem', color: msg.role === 'user' ? 'hsl(var(--color-primary))' : 'hsl(var(--color-text-muted))' }}>
                                            {msg.role === 'user' ? 'Claimant' : 'Voice Assistant'}
                                        </div>
                                        {msg.content}
                                    </div>
                                ))
                            ) : (
                                <div style={{ color: 'hsl(var(--color-text-muted))', fontStyle: 'italic' }}>No transcript available.</div>
                            )}
                        </div>
                    </div>
                </div>

                {/* Right Column */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                    {/* Status Card */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem' }}>Status</h3>
                        <div style={{
                            padding: '1rem', borderRadius: 'var(--radius-md)', textAlign: 'center',
                            backgroundColor: claimData.decision === 'Fast Track' ? 'hsl(var(--color-success) / 0.1)' : 'hsl(var(--color-warning) / 0.1)',
                            color: claimData.decision === 'Fast Track' ? 'hsl(var(--color-success))' : 'hsl(var(--color-warning))',
                            fontWeight: '700', fontSize: '1.25rem', border: '1px solid currentColor'
                        }}>
                            {claimData.decision}
                        </div>
                    </div>

                    {/* Status History */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem' }}>Status History</h3>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                            {claimData.statusHistory && claimData.statusHistory.length > 0 ? (
                                claimData.statusHistory.map((item, idx) => (
                                    <div key={idx} style={{ display: 'flex', gap: '0.75rem', fontSize: '0.85rem' }}>
                                        <div style={{
                                            width: '2px', backgroundColor: 'hsl(var(--color-primary))',
                                            position: 'relative', marginTop: '0.25rem'
                                        }}>
                                            <div style={{
                                                width: '8px', height: '8px', borderRadius: '50%',
                                                backgroundColor: 'hsl(var(--color-primary))',
                                                position: 'absolute', left: '-3px', top: '0'
                                            }}></div>
                                        </div>
                                        <div>
                                            <div style={{ fontWeight: '600' }}>{item.status}</div>
                                            <div style={{ color: 'hsl(var(--color-text-muted))', fontSize: '0.75rem' }}>
                                                {new Date(item.timestamp).toLocaleString()}
                                            </div>
                                            <div style={{ fontSize: '0.75rem', marginTop: '0.25rem' }}>
                                                {item.reason}
                                            </div>
                                            <div style={{ marginTop: '0.25rem' }}>
                                                <span style={{
                                                    fontSize: '0.65rem', padding: '0.1rem 0.4rem',
                                                    backgroundColor: 'hsl(var(--color-primary))', color: 'white',
                                                    borderRadius: 'var(--radius-sm)', fontWeight: '600'
                                                }}>
                                                    🤖 {item.actor.replace(' Agent', '').toUpperCase()}
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                ))
                            ) : (
                                <div style={{ color: 'hsl(var(--color-text-muted))', fontStyle: 'italic' }}>No history available.</div>
                            )}
                        </div>
                    </div>

                    {/* Documents Panel */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem' }}>Documents</h3>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem' }}>
                                <span>FNOL Report</span>
                                <span style={{ color: 'hsl(var(--color-success))' }}>✓ Received</span>
                            </div>
                            {claimData.documents?.map((doc, i) => (
                                <div key={i} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem' }}>
                                    <span style={{ textTransform: 'capitalize' }}>{doc.replace('_', ' ')}</span>
                                    <span style={{ color: 'hsl(var(--color-success))' }}>✓ Received</span>
                                </div>
                            ))}
                            {claimData.missingInfo?.map((doc, i) => (
                                <div key={i} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem' }}>
                                    <span style={{ textTransform: 'capitalize' }}>{doc.replace('_', ' ')}</span>
                                    <span style={{ color: 'hsl(var(--color-warning))' }}>⚠ Requested</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Actions */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem' }}>Actions</h3>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                            <button className="btn btn-primary" style={{ width: '100%' }}>Approve & Pay</button>
                            <button className="btn btn-secondary" style={{ width: '100%' }}>Assign Adjuster</button>
                            <button className="btn btn-secondary" style={{ width: '100%', color: 'hsl(var(--color-danger))', borderColor: 'hsl(var(--color-danger))' }}>Flag for SIU</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    )
}
