export default function ClaimBrief({ claimData, onReset }) {
    if (!claimData) return null

    return (
        <div className="fade-in">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
                <div>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: '700' }}>Claim Brief #{claimData.id}</h2>
                    <p style={{ color: 'hsl(var(--color-text-muted))' }}>Generated by Claim Brief Assembly Agent</p>
                </div>
                <button className="btn btn-secondary" onClick={onReset}>Close Brief</button>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '1.5rem' }}>

                {/* Left Column */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                    {/* Summary Card */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem', borderBottom: '1px solid hsl(var(--color-text-light) / 0.1)', paddingBottom: '0.5rem' }}>Claim Summary</h3>
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                            <div>
                                <label className="label">Claimant</label>
                                <div style={{ fontWeight: '500' }}>{claimData.name}</div>
                            </div>
                            <div>
                                <label className="label">Employee ID</label>
                                <div style={{ fontWeight: '500' }}>{claimData.employeeId}</div>
                            </div>
                            <div style={{ gridColumn: 'span 2' }}>
                                <label className="label">Incident Description</label>
                                <p style={{ lineHeight: '1.5' }}>{claimData.description}</p>
                            </div>
                        </div>
                    </div>

                    {/* Agent Reasoning Card */}
                    <div className="card" style={{ backgroundColor: 'hsl(var(--color-primary) / 0.05)', border: '1px solid hsl(var(--color-primary) / 0.2)' }}>
                        <h3 style={{ marginBottom: '1rem', color: 'hsl(var(--color-primary))' }}>🤖 Agent Reasoning</h3>
                        <p style={{ marginBottom: '1rem' }}>
                            Based on the reported <strong>{claimData.severity} damage</strong> and incident type, the Triage Agent has determined the following:
                        </p>

                        {/* Risk & Action Grid */}
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1.5rem' }}>
                            <div style={{ padding: '0.5rem 1rem', backgroundColor: 'white', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-sm)' }}>
                                <div className="label">Fraud Risk</div>
                                <div style={{
                                    fontSize: '1.25rem',
                                    fontWeight: '700',
                                    color: claimData.fraudRisk === 'High' ? 'hsl(var(--color-danger))' : claimData.fraudRisk === 'Medium' ? 'hsl(var(--color-warning))' : 'hsl(var(--color-success))'
                                }}>
                                    {claimData.fraudRisk || 'Low'}
                                </div>
                                <div style={{ fontSize: '0.75rem', color: 'hsl(var(--color-text-muted))', marginTop: '0.25rem' }}>
                                    {claimData.fraudReasoning || 'No inconsistencies detected.'}
                                </div>
                            </div>
                            <div style={{ padding: '0.5rem 1rem', backgroundColor: 'white', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-sm)' }}>
                                <div className="label">Recommended Action</div>
                                <div style={{ fontSize: '1.1rem', fontWeight: '600' }}>{claimData.recommendedAction}</div>
                            </div>
                        </div>

                        {/* Future Steps & Suggestions */}
                        {claimData.futureSteps && (
                            <div style={{ marginBottom: '1rem' }}>
                                <h4 style={{ fontSize: '0.9rem', fontWeight: '600', marginBottom: '0.5rem' }}>Future Steps for Company</h4>
                                <ul style={{ paddingLeft: '1.5rem', fontSize: '0.9rem', color: 'hsl(var(--color-text-main))' }}>
                                    {claimData.futureSteps.map((step, i) => (
                                        <li key={i} style={{ marginBottom: '0.25rem' }}>{step}</li>
                                    ))}
                                </ul>
                            </div>
                        )}

                        {claimData.employeeSuggestions && (
                            <div style={{ padding: '0.75rem', backgroundColor: 'hsl(var(--color-warning) / 0.1)', borderRadius: 'var(--radius-md)', border: '1px solid hsl(var(--color-warning) / 0.2)' }}>
                                <h4 style={{ fontSize: '0.9rem', fontWeight: '600', marginBottom: '0.5rem', color: 'hsl(var(--color-warning))' }}>💡 Employee Suggestions</h4>
                                <p style={{ fontSize: '0.9rem' }}>{claimData.employeeSuggestions}</p>
                            </div>
                        )}
                    </div>
                    {/* Official Report (if exists) */}
                    {claimData.officialReport && (
                        <div className="card" style={{ border: '1px solid hsl(var(--color-primary))', marginBottom: '1.5rem' }}>
                            <h3 style={{ marginBottom: '0.5rem', color: 'hsl(var(--color-primary))' }}>📄 Official Company Report</h3>
                            <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit', fontSize: '0.9rem', color: 'hsl(var(--color-text-main))' }}>
                                {claimData.officialReport}
                            </pre>
                        </div>
                    )}

                    {/* Transcript Viewer */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem' }}>💬 Conversation Transcript</h3>
                        <div style={{ maxHeight: '300px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.75rem', paddingRight: '0.5rem' }}>
                            {claimData.transcript && claimData.transcript.length > 0 ? (
                                claimData.transcript.map((msg, idx) => (
                                    <div key={idx} style={{
                                        alignSelf: msg.role === 'user' ? 'flex-end' : 'flex-start',
                                        backgroundColor: msg.role === 'user' ? 'hsl(var(--color-primary) / 0.1)' : 'hsl(var(--color-surface))',
                                        color: 'hsl(var(--color-text))',
                                        padding: '0.5rem 0.75rem',
                                        borderRadius: '0.5rem',
                                        maxWidth: '90%',
                                        fontSize: '0.85rem',
                                        border: msg.role === 'user' ? '1px solid hsl(var(--color-primary) / 0.2)' : '1px solid hsl(var(--color-border))'
                                    }}>
                                        <div style={{ fontSize: '0.7rem', fontWeight: '600', marginBottom: '0.25rem', color: msg.role === 'user' ? 'hsl(var(--color-primary))' : 'hsl(var(--color-text-muted))' }}>
                                            {msg.role === 'user' ? 'Claimant' : 'Voice Assistant'}
                                        </div>
                                        {msg.content}
                                    </div>
                                ))
                            ) : (
                                <div style={{ color: 'hsl(var(--color-text-muted))', fontStyle: 'italic' }}>No transcript available.</div>
                            )}
                        </div>
                    </div>
                </div>

                {/* Right Column */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                    {/* Status Card */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem' }}>Status</h3>
                        <div style={{
                            padding: '1rem', borderRadius: 'var(--radius-md)', textAlign: 'center',
                            backgroundColor: claimData.decision === 'Fast Track' ? 'hsl(var(--color-success) / 0.1)' : 'hsl(var(--color-warning) / 0.1)',
                            color: claimData.decision === 'Fast Track' ? 'hsl(var(--color-success))' : 'hsl(var(--color-warning))',
                            fontWeight: '700', fontSize: '1.25rem', border: '1px solid currentColor'
                        }}>
                            {claimData.decision}
                        </div>
                    </div>

                    {/* Documents Panel */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem' }}>Documents</h3>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem' }}>
                                <span>FNOL Report</span>
                                <span style={{ color: 'hsl(var(--color-success))' }}>✓ Received</span>
                            </div>
                            {claimData.documents?.map((doc, i) => (
                                <div key={i} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem' }}>
                                    <span style={{ textTransform: 'capitalize' }}>{doc.replace('_', ' ')}</span>
                                    <span style={{ color: 'hsl(var(--color-success))' }}>✓ Received</span>
                                </div>
                            ))}
                            {claimData.missingInfo?.map((doc, i) => (
                                <div key={i} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem' }}>
                                    <span style={{ textTransform: 'capitalize' }}>{doc.replace('_', ' ')}</span>
                                    <span style={{ color: 'hsl(var(--color-warning))' }}>⚠ Requested</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Actions */}
                    <div className="card">
                        <h3 style={{ marginBottom: '1rem' }}>Actions</h3>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                            <button className="btn btn-primary" style={{ width: '100%' }}>Approve & Pay</button>
                            <button className="btn btn-secondary" style={{ width: '100%' }}>Assign Adjuster</button>
                            <button className="btn btn-secondary" style={{ width: '100%', color: 'hsl(var(--color-danger))', borderColor: 'hsl(var(--color-danger))' }}>Flag for SIU</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    )
}
